// <auto-generated />
namespace OperationBier.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedGuidAuthorIds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedGuidAuthorIds));
        
        string IMigrationMetadata.Id
        {
            get { return "202109142138128_AddedGuidAuthorIds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
